package edu.orangecoastcollege.cs272.capstone.view;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.TextField;

import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Scanner;

import edu.orangecoastcollege.cs272.capstone.controller.Controller;
import edu.orangecoastcollege.cs272.capstone.model.SceneNavigation;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;

public class BMICalc implements SceneNavigation{
	
	private Controller mController = Controller.getInstance();
	private static final String FXML_FILE_NAME = "bmi_calc.fxml";
	private static String savedUser = "";

	
	
	@FXML
	private TextField weightTF;
	@FXML
	private TextField bmiTF;
	@FXML
	private TextField feetTF;
	@FXML
	private TextField inchesTF;
	
	// Event Listener on Button[#updateButton].onAction
	@FXML
	public void updateProfile(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancel() 
	{
		feetTF.clear();
		inchesTF.clear();
		weightTF.clear();
		bmiTF.clear();
		
		
	}
	
	// Event Listener on Button[#calcButton].onAction
	@FXML
	public void calculate() 
	{
		if(!feetTF.equals(null) && !inchesTF.equals(null) && !weightTF.equals(null))
		{
			Double a = Double.parseDouble(weightTF.getText()) * .45;
	        Double h = Double.parseDouble(feetTF.getText()) * 12;
	        Double b = Math.pow(((Double.parseDouble(inchesTF.getText()) + h) * .025), 2);
	        Double c = a / b;
	        
	        NumberFormat num = new DecimalFormat("#0.0");
	        bmiTF.setText((num.format(c).toString()));
		}
		else
			bmiTF.setText("Please try again");
	}
	
	// Event Listener on Label.onMouseClicked
	@FXML
	public void openBMICharts() {
		// TODO Autogenerated
	}

	@Override
	public Scene getView()
	{
		try {
			Scanner input = new Scanner(new File("resources/init.txt"));

			if (input.hasNextLine())
				savedUser = input.nextLine();
			input.close();

			AnchorPane ap = (AnchorPane) FXMLLoader.load(getClass().getResource(FXML_FILE_NAME));
			return new Scene(ap);

		} catch (IOException e) {
			e.printStackTrace();
			return null;
		}
	}
}
