package edu.orangecoastcollege.cs272.capstone.view;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class CalcHomePage {

	// Event Listener on Button.onAction
	@FXML
	public void goToBMIScene(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void goToBMRScene(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void goToBodyFatScene(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void goToHomeScene(ActionEvent event) {
		// TODO Autogenerated
	}
}
