package edu.orangecoastcollege.cs272.capstone.view;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.cs272.capstone.controller.Controller;
import edu.orangecoastcollege.cs272.capstone.model.SceneNavigation;

import javafx.scene.control.ListView;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;

public class FoodSearch implements SceneNavigation, Initializable{
	@FXML
	private ListView foodLV;
	@FXML
	private ComboBox filterCB;
	@FXML
	private TextField searchTF;
	
	private Controller mController = Controller.getInstance();
	private static final String FXML_FILE_NAME = "FoodSearch.fxml";

	// Event Listener on ComboBox[#filterCB].onAction
	@FXML
	public void filterFoodGroups() 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void foodSearch() 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void reset() 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addItemtoFD() 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void goToHomeScreen() 
	{
		HomePage page = new HomePage();
		mController.changeScene(page.getView(), true);
	}
	@Override
	public Scene getView()
	{
		try {
			BorderPane ap = (BorderPane) FXMLLoader.load(getClass().getResource(FXML_FILE_NAME));
			return new Scene(ap);

		} catch (IOException e) {
			e.printStackTrace();
			return null;
		}
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1)
	{
		// TODO Auto-generated method stub
		
	}
}
